### PR TITLE
Initial Tokenizing and parsing into Expressions

### PR DESCRIPTION
**Pull request by AurumTheEnd**

### CODE REVIEW

**Comment by daemontus** [comment]
This is not related to the new code, but I missed this during the last "review". I'm writing it down so that I don't forget about it.

For semantic equality, it is not necessarily valid to return `false` when `self_literals != other_literals`. Counterexample: `a & b & (c | !c)` is semantically equivalent to `a & b`.

**Comment by daemontus** [comment]
Discussion question: How hard would it be to have a position in the original string associated with each error? I'm guessing we'll need to add some kind of `position` field to each token and then we can report that? Motivation: I can print "Error is here", not just "there is an error".

**Review by daemontus — APPROVED** [review]

**Comment by AurumTheEnd** [comment]
> This is not related to the new code, but I missed this during the last "review". I'm writing it down so that I don't forget about it.
> 
> For semantic equality, it is not necessarily valid to return `false` when `self_literals != other_literals`. Counterexample: `a & b & (c | !c)` is semantically equivalent to `a & b`.

Very good point, will fix :+1:

**Comment by AurumTheEnd** [comment]
> Discussion question: How hard would it be to have a position in the original string associated with each error? I'm guessing we'll need to add some kind of `position` field to each token and then we can report that? Motivation: I can print "Error is here", not just "there is an error".

Not hard at all, the `thiserror` crate is quite powerful (it's just that the documentation is a bit sparse). Will fix!

**Comment by AurumTheEnd** [comment]
For discussion:

- how to reconcile multi-char variable names
- how to reconcile multi-char operator names
  - having `"false"` as an operator prevents `"false"` to be used as a substring anywhere in variables, same goes for `F` or `not`... (aside from the `{false}` notation)
  - having both `&` and `&&` operators results in parsing `"a && b"` as `"a and and b"`

**Comment by AurumTheEnd** [comment]
Side note: coming from Gitlab, it's unbelievable that Github doesn't have conversation threads 😮‍💨

**Comment by AurumTheEnd** [comment]
@daemontus After yesterdays changes, I added some tests to increase coverage.

Could you please re-review before we merge this?

**Comment by daemontus** [comment]
One more thing, and then I believe we are done :)

We need some kind of generic "UnknownSymbol" token error. Right now, parsing something like "@", or "and$", or "\<foo\>" just loops forever, because we detect an empty literal and cannot move to the next character. I think it should be sufficient to have an emptiness check in `consume_while_literal` and throw the "UnknownSymbol" error there. Or alternatively put it in the main `match` expression in the `tokenize_level` function.

**Pull request merged**
